### PR TITLE
bad merge fix + ignore casing -> false

### PR DESCRIPTION
**Pull request by mmamel**
jesus `git config core.ignorecase` was set to true

### CODE REVIEW

**Comment by mmamel** [comment]
Should the checks be passing? Or what is it checking

**Comment by nickywongdong** [comment]
> Should the checks be passing? Or what is it checking

it's just running an npm run build, and npm run test

**Comment by mmamel** [comment]
I'm gonna flip out if git doesn't automatically replace the icon folder with Icon lol

**Comment by mmamel** [comment]
hm, npm run test passes the 1 test we have

**Comment by nickywongdong** [comment]
> I'm gonna flip out if git doesn't automatically replace the icon folder with Icon lol

you can go ahead and merge, i'm still fixing the pipeline

**Comment by mmamel** [comment]
GDI why is this git so stupid. the icon folder is still there and I cant delete it from my local cuz it doesnt exist

**Comment by nickywongdong** [comment]
> GDI why is this git so stupid. the icon folder is still there and I cant delete it from my local cuz it doesnt exist

yeah that's weird, i dont even see it in mine

**Comment by nickywongdong** [comment]
> GDI why is this git so stupid. the icon folder is still there and I cant delete it from my local cuz it doesnt exist

oh it's gone now.. guess it was just delayed

**Comment by mmamel** [comment]
im just manually deleting it from github, maybe it has to do some symlink logic

**Comment by mmamel** [comment]
No i had to do it via the ui, I couldn't do it from visual studio

**Comment by mmamel** [comment]
or maybe its visual studio thats the problem...

**Comment by nickywongdong** [comment]
dunno, i'm using git cli

**Pull request merged**
